# Data transformation

```{r}
library(tidyverse)
library(rvest)
```

## Web Scraping

```{r}
extract_table_poc <- function(html, n) {
  #extract nth table from html
  nth_table <- html %>%
    html_nodes(css = "table") %>% 
    nth(n) %>% 
    html_table(fill = TRUE)
  
  colnames(nth_table) <- nth_table[2,]
  nth_table <- nth_table[3:nrow(nth_table),]
  
  return(nth_table)
}

extract_table <- function(html, n) {
  #extract nth table from html
  nth_table <- html %>%
    html_nodes(css = "table") %>% 
    nth(n) %>% 
    html_table(fill = TRUE)
  
  return(nth_table)
}
```


```{r}
#black lead/supporting actors and actresses
black_actors_html = read_html("https://en.wikipedia.org/wiki/List_of_black_Academy_Award_winners_and_nominees")

black_actor_lead <- extract_table_poc(black_actors_html, 2)
black_actress_lead <- extract_table_poc(black_actors_html, 3)
black_actor_sup <- extract_table_poc(black_actors_html, 4)
black_actress_sup <- extract_table_poc(black_actors_html, 5)
```

```{r}
#latin lead/supporting actors and actress
latin_actors_html <- read_html("https://en.wikipedia.org/wiki/List_of_Latin_American_Academy_Award_winners_and_nominees")

latin_actor_lead <- extract_table_poc(latin_actors_html, 4) %>% select(Year, Nominee, Film, Result)
latin_actress_lead <- extract_table_poc(latin_actors_html, 5) %>% select(Year, Nominee, Film, Result)
latin_actor_sup <- extract_table_poc(latin_actors_html, 6) %>% select(Year, Nominee, Film, Result)
latin_actress_sup <- extract_table_poc(latin_actors_html, 7) %>% select(Year, Nominee, Film, Result)
```

```{r}
#asian lead/supporting actors and actress
asian_actors_html <- read_html("https://en.wikipedia.org/wiki/List_of_Asian_Academy_Award_winners_and_nominees")

asian_actors_html %>%
    html_nodes(css = "table") %>% 
    nth(2) %>% 
    html_table(fill = TRUE)

asian_actor_lead <- extract_table_poc(asian_actors_html, 2) %>% select(Year, Name, Film, Status)
asian_actress_lead <- extract_table_poc(asian_actors_html, 3) %>% select(Year, Name, Film, Status)
asian_actor_sup <- extract_table_poc(asian_actors_html, 4) %>% select(Year, Name, Film, Status)
asian_actress_sup <- extract_table_poc(asian_actors_html, 5) %>% select(Year, Name, Film, Status)

#egyptian
egyptian_actor_lead <- data.frame(Year = "2018", Name = "Rami Malek", Film = "Bohemian Rhapsody", Status = "Won")
```


```{r}
#all supporting actors
actor_sup_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Supporting_Actor")

actor_sup <- NULL
for(i in 3:12) {
  actor_sup <- rbind(actor_sup, extract_table(actor_sup_html, i))
}


#all supporting actresses
actress_sup_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Supporting_Actress")

actress_sup <- NULL
for(i in 3:12) {
  actress_sup <- rbind(actress_sup, extract_table(actress_sup_html, i))
}
actress_sup <- actress_sup %>% drop_na()
```


```{r}
#all lead actors
actor_lead_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actor")

actor_lead <- NULL
for(i in 3:13) {
  actor_lead <- rbind(actor_lead, extract_table(actor_lead_html, i))
}


#all lead actress
actress_lead_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actress")

actress_lead <- NULL
for(i in 3:13) {
  actress_lead <- rbind(actress_lead, extract_table(actress_lead_html, i))
}
```


```{r}
latin_actors_html %>%
    html_nodes(css = "table") %>% 
    nth(6) %>% 
    html_table(fill = TRUE)
```



###  Highest Grossing Movies from 1977-2021

```{r}
link1 <- "https://www.boxofficemojo.com/year/world/"
link2 <- "/?sort=domesticGrossToDate&ref_=bo_ydw__resort#table"

#highest_grossing <- NULL

# for(i in 1977:2021) {
#   temp_link <- paste(link1, as.character(i), link2, sep="")
#   temp_html <- read_html(temp_link)
#   movie_table <- temp_html %>% html_nodes("table") %>% html_table(fill = T)
#   movie <- movie_table[[1]][1,]
#   highest_grossing <- rbind(highest_grossing, movie) 
# }

highest_grossing <- data.frame(Movie=character(45), Domestic=character(45))
index <- 1

for(i in 1977:2021) {
  temp_link <- paste(link1, as.character(i), link2, sep="")
  temp_html <- read_html(temp_link)
  highest_grossing$Movie[index] <- temp_html %>% html_nodes("td") %>% html_text %>% nth(2)
  highest_grossing$Domestic[index] <- temp_html %>% html_nodes("td") %>% html_text %>% nth(4)
  index <- index + 1
}

highest_grossing <- highest_grossing %>% mutate(Year = 1977:2021) %>% rename(Overall_Movie = Movie, Overall_Boxoffice = Domestic) 
#coverting boxoffice to numeric
highest_grossing$Overall_Boxoffice <- as.numeric(gsub("\\$|,", "", highest_grossing$Overall_Boxoffice))
```


### Box office earnings of Oscar Best Picture
```{r}
oscar_bo_html <- read_html("https://www.the-numbers.com/movies/comparisons/Best-Picture-Oscar-Winners")

oscar_bo <- (oscar_bo_html %>% html_nodes("table") %>% html_table(fill = T))[[1]]
oscar_bo <- oscar_bo %>% select(Movie, "DomesticBox Office", "Release Date") %>% rename(Oscar_Boxoffice = "DomesticBox Office", "Oscar_Movie" = Movie)

#adding release year
oscar_bo$Year <- as.numeric(substr(oscar_bo$`Release Date`, nchar(oscar_bo$`Release Date`)-3, nchar(oscar_bo$`Release Date`)))
#coverting boxoffice to numeric
oscar_bo$Oscar_Boxoffice <- as.numeric(gsub("\\$|,", "", oscar_bo$Oscar_Boxoffice))
```


### Oscar Winners with female lead
```{r}
library(readxl)
female_winners<- read_xlsx("data/women.xlsx")

```

### Box office of Winners with female lead and the Nominees that year 
```{r}
female_nom_bo<-read_xlsx("data/female_nominees_bo.xlsx")
female_nom_bo
```
