# Results

```{r}
library(tidyverse)
library(stringr)
library(plotly)
library(shiny)
library(shinydashboard)
```


## Popular movies vs Oscar Winners 

```{r}
#manipulating tables
bo_oscar_highest_data <- left_join(oscar_bo, highest_grossing, by="Year") %>% select(Year, Overall_Movie, Overall_Boxoffice, Oscar_Movie, Oscar_Boxoffice)

rows <- nrow(bo_oscar_highest_data)

bo_oscar_temp <- bo_oscar_highest_data %>% select(Year, Oscar_Boxoffice, Oscar_Movie) %>% rename(Boxoffice = Oscar_Boxoffice, Movie = Oscar_Movie) %>% mutate(Group = rep("Oscar", rows))
bo_overall_temp <- bo_oscar_highest_data %>% select(Year, Overall_Boxoffice, Overall_Movie) %>% rename(Boxoffice = Overall_Boxoffice, Movie = Overall_Movie) %>% mutate(Group = rep("Overall", rows))

bo_oscar_highest_data <- rbind(bo_oscar_temp, bo_overall_temp)
```

```{r}
#plotting
bo_oscar_highest_data %>% 
  ggplot(aes(x = Year, y = Boxoffice, col = Group)) + 
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma) +
  theme_light() +
  scale_color_manual(values = c("#FAC983", "#000000")) +
  theme(legend.title= element_blank())


plot_ly() %>%
  add_lines(x = bo_oscar_temp$Year, y = bo_oscar_temp$Boxoffice, 
            color = I("#FAC983"), 
            name = "Oscar Best Picture",
            text = bo_oscar_temp$Movie,
            hoverinfo = 'text') %>%
  add_lines(x = bo_oscar_temp$Year, y = bo_overall_temp$Boxoffice, 
            color = I("black"), 
            name = "Highest Grossest Film",
            text = bo_overall_temp$Movie,
            hoverinfo = 'text') %>%
  layout(legend = list(x = 100, y = 0.5), title = 'Best Picture vs Highest Grossing Boxoffice')
```


## IMDB Ratings of Oscar Movies over Time

```{r}
# Dashboard ----------------------------------------------------------------
ui <- dashboardPage(
  dashboardHeader(title = "Test"),
  dashboardSidebar(),
  dashboardBody(tags$head(tags$style(
    HTML("img.small-img {
          max-width: 75px;
          }")
  )),
  plotlyOutput("hoverplot"))
)

server <- function(input, output, session) {
  output$hoverplot <- renderPlotly({
    plot_ly(
      imdb_oscar,
      x         = ~ Year,
      y         = ~ Rating,
      type      = 'scatter',
      mode      = 'markers',
      hoverinfo = 'none',
      source = "hoverplotsource",
      customdata = ~ Image
    ) %>%
      event_register('plotly_hover') %>%
      event_register('plotly_unhover')
  })

  hover_event <- reactive({
    event_data(event = "plotly_hover", source = "hoverplotsource")
  })

  unhover_event <- reactive({
    event_data(event = "plotly_unhover", source = "hoverplotsource")
  })

  hoverplotlyProxy <- plotlyProxy("hoverplot", session)

  observeEvent(unhover_event(), {
    hoverplotlyProxy %>%
      plotlyProxyInvoke("relayout", list(images = list(NULL)))
  })

  observeEvent(hover_event(), {
    hoverplotlyProxy %>%
      plotlyProxyInvoke("relayout", list(images = list(
        list(
          source = hover_event()$customdata,
          xref = "x",
          yref = "y",
          x = hover_event()$x,
          y = hover_event()$y,
          sizex = 20,
          sizey = 20,
          opacity = 1
        )
      )))
  })
}

shinyApp(ui = ui, server = server)
```


## Total Nominations and Wins of actors

```{r}
#data cleaning
all_actors <- data.frame(Actors = c(actor_lead$Actor, actor_sup$Actor))
all_actors_filter <- as.data.frame(table(all_actors))
all_actors_filter <- all_actors_filter %>% filter(Freq > 4)
all_actors <- all_actors %>% filter(Actors %in% all_actors_filter$all_actors)
```

```{r}
theme_oscars = function(base_size = 12, grid_width = 0.2) {
  bg_rect = element_rect(fill = "#dfca4e", color = "#dfca4e")

  theme_bw(base_size) +
    theme(
          plot.background = bg_rect,
          legend.background = bg_rect,
          panel.background = bg_rect,
          panel.grid.major = element_line(colour = "#3c3030", size = grid_width),
          panel.grid.minor = element_line(colour = "#3c3030", size = grid_width),
          legend.key.width = unit(1.5, "line"),
          legend.key = element_blank(),
          axis.title.x = element_text(margin = unit(c(0.5, 0.25, 0.5, 0.25), "line")),
          axis.title.y = element_text(margin = unit(c(0, 1, 0, 0.1), "line")),
          axis.ticks = element_blank(),
          panel.border = element_blank())
}
```

```{r}
#plotting
all_actors %>% 
  ggplot(aes(x=fct_rev(fct_infreq(Actors)))) + 
  geom_bar(fill="black") + 
  coord_flip() +
  ylab("# of Oscar Nominations") +
  theme_oscars(base_size = 10, grid_width = 0.4) +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(size = 15),
    plot.subtitle = element_text(hjust = 1.38, margin = unit(c(0.25, 0.25, 2, 0.25), "line")),
    axis.text.y = element_text(size = 10, margin = unit(c(0, -1, 0, 0), "line")),
    axis.title.y = element_blank(),
    axis.title.x = element_text(size = 10),
    legend.position = "none"
  )
  #ggtitle("Number of time Actors were Nominated for an Oscar")
```


## Total Nominations and Wins of actors

```{r}
#data cleaning
all_actress <- data.frame(Actress = c(actress_lead$Actress, actress_sup$Actress))
all_actress_filter <- as.data.frame(table(all_actress))
all_actress_filter <- all_actress_filter %>% filter(Freq > 4)
all_actress <- all_actress %>% filter(Actress %in% all_actress_filter$all_actress)
```


```{r}
#plotting
all_actress %>% 
  ggplot(aes(x=fct_rev(fct_infreq(Actress)))) + 
  geom_bar(fill="black") + 
  coord_flip() +
  ylab("# of Oscar Nominations") +
  theme_oscars(base_size = 10, grid_width = 0.4) +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(size = 15),
    plot.subtitle = element_text(hjust = 1.38, margin = unit(c(0.25, 0.25, 2, 0.25), "line")),
    axis.text.y = element_text(size = 10, margin = unit(c(0, -1, 0, 0), "line")),
    axis.title.y = element_blank(),
    axis.title.x = element_text(size = 10),
    legend.position = "none"
  )
  #ggtitle("Number of time Actors were Nominated for an Oscar")
```


