# Conclusion

Through this project, we were able to gain the insights to answer our initial questions:
- Was there racial bias present when it came to choosing what movies were considered “good”? 
- Are movies that have female lead roles as popular as those that have male lead roles?

By exploring the data of the race of the nominees and winners of Best Actor over the years, we were able to find out that the number of people of color nominated has significantly increased over the years. The rate of the increase has accelerated towards recent years, and the diversity has also improved, especially with black actors. Based on our analysis, we could conclude that there has been racial bias towards white actors in the movie industry indicated by Oscars settings, and it has started to change quite recently. Another takeaway of this project was figuring out that only approximately 17% of the Best Picture winners over the years was awarded to movies with female leads. This might have been caused both by the fact the number of movies with female leads are much less than those with male leads and that they have not been recognized enough by Oscars. While the proportion of people of color nominated for Best Actors has increased over time and it is continuing until now, the last Best Picture winner with female role was Million Dollar Baby in 2005 and there has been no more of such case since then. In addition, the winners with female leads do not necessarily have the highest box office earnings among other nominees that year. In the process of the analysis, we also found out that Oscar nominated movies mostly have ratings higher than 7, which indicates that people perceive those as decent movies, but almost none of them had the highest box office earnings that corresponding year. 

For this project, we created a custom theme for the graphs, only using color scheme that is accessible to people with color deficiency. We learned that collecting data that are appropriate for our purpose and cleaning them to make into specific forms we want takes the most time and effort for exploratory data analysis and data visualization. 

**Limitations:** 

- One of the future directions of this project could be analyzing the race of the nominees and winners of Best Actress over the years and comparing the graph with that of Best Actor to see if there is any difference in the changes by gender. 

- We would have also liked to examine the difference between the IMDB ratings of female lead movies and the male lead movies. We believe that would also give us some interesting insights.

- Another aspect of analysis that we wanted to do was related to the genre of movies. We wanted to see the relation of genres with race and sex to ask questions like - "Are actors of colors typecasted to certain genres or kind of roles?". We also wanted to see of any genre of movie is more likely to be win an Oscar over others. So we could have extended the scope of our project to include this too. 
