--- 
title: "Oscars Over the Years"
author: "Zoey Wee & Shreya Rao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We hear a lot of coverstaion surrounding diversity and inclucivity all around the world. Now there is an increasing number of people belonging to minority groups in positions of prominence. Movies are such a central part of our world and is almost a represenattion of us as a socity throughtout history. Since both of us are movie lovers, we were decided to focus on analyzing trends of diversity in movies. Movies are so universally loved, so we believe that asking questions in this context is the best way to spark these important conversations. Since the Oscars is synonomous with movies, we decided to study a couple of aspects of the Oscars over the years. 

Two pivotal questions were had were: 
1)	Is there a racial disparity among actors? 
2)	Are movies that have female lead roles as popular as those that have male lead roles?

After collecting our data and pondering more about questions we wanted answers to, we decided to broaden our Oscar analysis to include a wider and more general overview of the Oscars while also answering the above two questions.  

In order to gain insights, we first tried to look for a relationship between the “popularity” and “goodness” of movies. We assumed the goodness of a movie is determined by Oscar nominations and wins, and popularity is quantified by box office success. We also explored if there is a relationship between the number of times actors were nominationed and whether they actually win the award or not. Next, we explored how the proportion of actors of color nominted for an Oscar has changed over the years. Finally, we tried to figure out whether there has been gender disparity in the setting of Oscars and box office as well. We believe that this project can serve as a positive agent catalyzing healthy discussions about the media industry and our society as well. 