```{r}
library(tidyverse)
library(rvest)
```

## Web Scraping
```{r}
extract_table_b <- function(html, n) {
  #extract nth table from html
  nth_table <- html %>%
    html_nodes(css = "table") %>% 
    nth(n) %>% 
    html_table(fill = TRUE)
  
  colnames(nth_table) <- nth_table[2,]
  nth_table <- nth_table[3:nrow(nth_table),]
  return(nth_table)
}

extract_table <- function(html, n) {
  #extract nth table from html
  nth_table <- html %>%
    html_nodes(css = "table") %>% 
    nth(n) %>% 
    html_table(fill = TRUE)
  
  return(nth_table)
}
```

```{r}
#black lead/supporting actors and actresses
black_actors_html = read_html("https://en.wikipedia.org/wiki/List_of_black_Academy_Award_winners_and_nominees")

black_actor_lead <- extract_table_b(black_actors_html, 2)
black_actress_lead <- extract_table_b(black_actors_html, 3)
black_actor_sup <- extract_table_b(black_actors_html, 4)
black_actress_sup <- extract_table_b(black_actors_html, 5)


#all supporting actresses
actress_sup_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Supporting_Actress")

actress_sup <- NULL
for(i in 3:12) {
  actress_sup <- rbind(actress_sup, extract_table_sup(actress_sup_html, i))
}
actress_sup <- actress_sup %>% drop_na()


#all supporting actors
actor_sup_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Supporting_Actor")

actor_sup <- NULL
for(i in 3:12) {
  actor_sup <- rbind(actor_sup, extract_table(actor_sup_html, i))
}


#all lead actors
actor_lead_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actor")

actor_lead <- NULL
for(i in 3:13) {
  actor_lead <- rbind(actor_lead, extract_table(actor_lead_html, i))
}


#all lead actress
actress_lead_html <- read_html("https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actress")

actress_lead <- NULL
for(i in 3:13) {
  actor_lead <- rbind(actor_lead, extract_table(actor_lead_html, i))
}

actor_lead_html %>%
    html_nodes(css = "table") %>%
  nth(13) %>% 
    html_table(fill = TRUE)
```

